name: PvPGame
version: ${project.version}
main: de.marvinleiers.pvpgame.PvPGame
api-version: 1.15
authors: [Marvin2k0]
website: www.marvinleiers.de

commands:
  pvp:
    permission: pvp.admin
  challenge:
